### ISSUE TITLE
"Must have non-zero number of input Soy file"

### ISSUE THREAD

**Issue by G0dC0der** [wibidata/soy-maven-plugin#3]
I get the following message:

_[ERROR] Failed to execute goal com.odiago.maven.plugins:soy-maven-plugin:1.0.0:compile (default-cli) on project OnlineBooking: Execution default-cli of goal com.odiago.maven.plugins:soy-maven-plugin:1.0.0:compile failed: Must have non-zero number of input Soy files. -> [Help 1]_

I dont know what it means.
Here is my POM:
http://pastebin.com/zg9ck1CU

**Comment by ppasler** [comment]
@PojahnM How did you solve this?
